- id: '1517693010922'
  alias: Fajr Adhan
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d"))
        == as_timestamp(strptime(states("sensor.islamic_prayer_time_fajr"), "%Y-%m-%dT%H:%M:%S")) }}'
  condition: []
  action:
  - alias: ''
    data:
      entity_id:
      - media_player.******
      media_content_id: https://www.youtube.com/watch?v=Zn4cynlzt4A
      media_content_type: audio/mp3
    service: media_extractor.play_media
  - data:
      entity_id:
      - media_player.******
      volume_level: '0.5'
    service: media_player.volume_set

id: '1517693010923'
  alias: Adhan
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d"))
        == as_timestamp(strptime(states("sensor.islamic_prayer_time_dhuhr"), "%Y-%m-%dT%H:%M:%S")) }}'
  - platform: template
    value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d"))
        == as_timestamp(strptime(states("sensor.islamic_prayer_time_asr"), "%Y-%m-%dT%H:%M:%S")) + (60 * 60) }}'
  - platform: template
    value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d"))
        == as_timestamp(strptime(states("sensor.islamic_prayer_time_maghrib"), "%Y-%m-%dT%H:%M:%S")) }}'
  - platform: template
    value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d"))
        == as_timestamp(strptime(states("sensor.islamic_prayer_time_isha"), "%Y-%m-%dT%H:%M:%S")) }}'
  condition: []
  action:
  - alias: ''
    data:
      entity_id:
      - media_player.******
      media_content_id: https://www.youtube.com/watch?v=EZgPnLEBTn8
      media_content_type: audio/mp3
    service: media_extractor.play_media
  - data:
      entity_id:
      - media_player.******
      volume_level: '0.5'
    service: media_player.volume_set
