# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://*****.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: https://*****.duckdns.org:8123
    service_name: google_say

discovery:
  ignore:
    - yeelight
    
media_extractor:
sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  latitude: 00.00
  longitude: 00.00
  elevation: 000
  unit_system: metric
  time_zone: America/Chicago
  
zone:
  - name: Home
    latitude: 00.00
    longitude: 00.00
    radius: 25
    icon: mdi:home

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: islamic_prayer_times
    calculation_method: isna
    sensors:
      - fajr
      - sunrise
      - dhuhr
      - asr
      - maghrib
      - isha
      - midnight
      
yeelight:
  devices:
    192.168.0.xxx:
      name: *****
